name: Test Canister

on:
  push:
  pull_request:

env:
  vessel_version: "v0.6.3"
  moc_version: "0.5.14"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.10.0
          vessel-version: 0.6.3
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Canister test suite
        run: |
          npm i
          npm run make-admin
          npm run test:dfx
